before_install:
    - sudo add-apt-repository --yes ppa:beineri/opt-qt55
    - sudo apt-get update -qq
    - sudo apt-get install -qq qt-latest

script:
    - source /opt/qt55/bin/qt55-env.sh
    - qmake -v
    - qmake
    - make

