before_install:
    - sudo add-apt-repository --yes ppa:beineri/opt-qt55
    - sudo apt-get update -qq
    - sudo apt-get install -qq qt55-meta

script:
    - source /opt/qt54/bin/qt54-env.sh
    - qmake -qt=qt5 -v
    - qmake -qt=qt5
    - make

